name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: DoSomething
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libbrotli1\
          libegl1\
          libopus0\
          libwoff1\
          libgstreamer-plugins-base1.0-0\
          libgstreamer1.0-0\
          libgstreamer-gl1.0-0\
          libgstreamer-plugins-bad1.0-0\
          libopenjp2-7\
          libwebpdemux2\
          libhyphen0\
          libgles2\
          gstreamer1.0-libav
    - name: DoSomething
      run: |
        mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: "**/*png"