name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: DoSomething
      run: |
        mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot
        ls -la
        find .
